title: Richard Adleta
domain: www.richardadleta.com
baseurl: ""
url: https://www.richardadleta.com
github_username: radleta

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

description: "Richard Adleta, Hands-On Senior Software Architect & Full-Stack Engineer, passionate about hands-on coding, AI, and building innovative, scalable software solutions."

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - "*.sh"
  - _source

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:title
  posts:
    output: true
    permalink: /:collection/:title
  resume:
    output: true
    permalink: /:collection/:title
  downloads:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: resume
    values:
      author_profile: true
      share: true
      sidebar:
        nav: resume

author:
  name: "Richard Adleta"
  email: "radleta@gmail.com"
  avatar: "/assets/images/radleta_headshot_v3.jpg"
  bio: "Senior Software Architect & Full-Stack Engineer"
  location: "Dallas, TX"
  website: "https://www.richardadleta.com"
  links:
    - label: "About Me"
      icon: "fas fa-fw fa-user"
      url: "/about"
    - label: "Resume"
      icon: "fas fa-fw fa-file-alt"
      url: "/resume"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/radleta"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/radleta"

footer:
  links:
    - label: "About Me"
      icon: "fas fa-fw fa-user"
      url: "/about"
    - label: "Resume"
      icon: "fas fa-fw fa-file-alt"
      url: "/resume"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/radleta"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/radleta"
    - label: "Posts"
      icon: "fas fa-fw fa-pen"
      url: "/posts"
